---
# subway-api HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subway-api-hpa
  namespace: metrohub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subway-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
# subway-notification HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subway-notification-hpa
  namespace: metrohub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subway-notification
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
# subway-web HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subway-web-hpa
  namespace: metrohub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subway-web
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
