apiVersion: v1
kind: Service
metadata:
  name: subway-notification
  namespace: metrohub
spec:
  selector:
    app: subway-notification
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
